baseURL = "http://gretl-assoc.github.io/"
languageCode = "en-us"
# title = "Gretl Association"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Willkommen bei der Gretl Association"
    weight = 1
    contentDir = "content/fr"
  [languages.en]
    title = "Welcome to the Gretl Association"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  toc = true
  # body_classes = "avenir bg-near-white"
  # site_logo = "static/header_images.png"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  instagram = ""
  youtube = ""
  github = "https://github.com/gretl-assoc"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2
