baseURL = "http://gretl-assoc.github.io/"
languageCode = "de"
# title = "gretl Association"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "gretl Association"
    weight = 1
    contentDir = "content/de"
    languageName = "Deutsch"
  [languages.en]
    title = "gretl Association"
    weight = 2
    contentDir = "content/en"
    languageName = "English"

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params]
  toc = true
  # body_classes = "avenir bg-near-white"
  # site_logo = "static/header_images.png"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  instagram = ""
  youtube = ""
  github = "https://github.com/gretl-assoc"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-blue"
  # featured_image = "/images/isaac-smith-AT77Q0Njnt0-unsplash-1.jpg"
  # featured_image = "/images/joshua-sortino-LqKhnDzSF-8-unsplash.jpg"
  featured_image = "/images/pietro-jeng-n6B49lTx7NM-unsplash.jpg"
  recent_posts_number = 2


[[languages.de.menu.main]]
  [[menu.main]]
    identifier = "gretl"
    name = "gretl"
    url = "/gretl"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Über uns"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "member"
    name = "Mitgliedschaft"
    url = "/member"
    weight = 3
  [[menu.main]]
    identifier = "dates"
    name = "Termine"
    url = "/dates"
    weight = 4

[[languages.en.menu.main]]
  [[menu.main]]
    identifier = "gretl"
    name = "gretl"
    url = "/gretl"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About us"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "member"
    name = "Members"
    url = "/member"
    weight = 3
  [[menu.main]]
    identifier = "dates"
    name = "Dates"
    url = "/dates"
    weight = 4
