baseURL = "http://gretl-assoc.github.io/"
languageCode = "de"
# title = "Gretl Association"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Willkommen bei der gretl Association e.V."
    weight = 1
    contentDir = "content/de"
    languageName = "Deutsch"
  [languages.en]
    title = "Welcome to the gretl Association e.V."
    weight = 1
    contentDir = "content/en"
    languageName = "English"

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params]
  toc = true
  # body_classes = "avenir bg-near-white"
  # site_logo = "static/header_images.png"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  instagram = ""
  youtube = ""
  github = "https://github.com/gretl-assoc"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2


[[languages.de.menu.main]]
  [[menu.main]]
    identifier = "about"
    name = "Über uns"
    url = "/about"
    weight = 1
  [[menu.main]]
    identifier = "member"
    name = "Mitgliedschaft"
    url = "/member"
    weight = 2
  [[menu.main]]
    identifier = "dates"
    name = "Termine"
    url = "/dates"
    weight = 3
  [[menu.main]]
    identifier = "docs"
    name = "Dokumente"
    url = "/docs"
    weight = 4
  [[menu.main]]
    identifier = "donation"
    name = "Spenden"
    url = "/donation"
    weight = 5
  [[menu.main]]
    identifier = "grant"
    name = "Stipendium"
    url = "/grant"
    weight = 1

[[languages.en.menu.main]]
  [[menu.main]]
    identifier = "about"
    name = "About us"
    url = "/about"
    weight = 1
  [[menu.main]]
    identifier = "member"
    name = "Members"
    url = "/member"
    weight = 2
  [[menu.main]]
    identifier = "dates"
    name = "Dates"
    url = "/dates"
    weight = 3
  [[menu.main]]
    identifier = "docs"
    name = "Documents"
    url = "/docs"
    weight = 4
  [[menu.main]]
    identifier = "donation"
    name = "Donation"
    url = "/donation"
    weight = 5
  [[menu.main]]
    identifier = "grant"
    name = "Grant"
    url = "/grant"
    weight = 1
